gafaelfawr:
  imagePullSecrets:
    - name: "pull-secret"
  ingress:
    host: rsp.lapp.in2p3.fr
  vaultSecretsPath: "secret/k8s_operator/rsp-lapp/gafaelfawr"

  # Reset token storage on every Redis restart.
  redis:
    persistence:
      enabled: false

  config:
    host: "rsp.lapp.in2p3.fr"

    github:
      clientId: "bf216316caab0dfa2127"

    # Allow access by GitHub team.
    groupMapping:
      "exec:admin":
        - "lsst-france-calcul"
      "exec:user":
        - "lsst-france-calcul"
      "read:workspace":
        - "lsst-france-calcul"
      "read:workspace/user":
        - "lsst-france-calcul"
      "write:workspace/user":
        - "lsst-france-calcul"
      "exec:portal":
        - "lsst-france-calcul"
      "exec:notebook":
        - "lsst-france-calcul"
      "read:tap":
        - "lsst-france-calcul"
      "read:image":
        - "lsst-france-calcul"

  # Use CILogon authentication.
  #cilogon:
  #  client_id: "cilogon:/client_id/74e865cd71a3a327096d36081166b739"
  #  redirect_url: "https://rsp.lapp.in2p3.fr/login"
  # login_params:
  #    skin: "LSST"

pull-secret:
  enabled: true
  path: secret/k8s_operator/rsp-lapp/pull-secret


