nublado2:
  jupyterhub:
    debug:
      enabled: true

    singleuser:
      storage:
        type: none

    ingress:
      hosts: ["dboutigny.freeboxos.fr"]
      annotations:
        nginx.ingress.kubernetes.io/auth-signin: "https://dboutigny.freeboxos.fr/login"
        nginx.ingress.kubernetes.io/auth-url: "https://dboutigny.freeboxos.fr/auth?scope=exec:notebook&notebook=true"

  config:
    base_url: "dboutigny.freeboxos.fr/"

    volumes:
      - name: data
        nfs:
          path: /data
          server: 192.168.0.69
      - name: home
        nfs:
          path: /jhome
          server: 192.168.0.69
    volume_mounts:
      - name: data
        mountPath: /data
      - name: home
        mountPath: /home

  vault_secret_path: "secret/k8s_operator/dboutigny.freeboxos.fr/nublado2"
  gafaelfawr_secret_path: "secret/k8s_operator/dboutigny.freeboxos.fr/gafaelfawr"